# This YAML file defines a GitHub Actions workflow designed to test and deploy a Python script to a remote virtual machine (VM) via SSH.

name: Test and Deploy Python Script

on: # When this happens, run this workflow.
  push: # Which workflow should be triggered when code is pushed to the repository.
    branches: # Which branches should trigger the workflow.
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Bash script tests
      run: |
        chmod +x ./testScript.sh &&  ./testScript.sh



  deploy:  # Could be "test" as well.
    runs-on: ubuntu-latest # Type of runner
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Name of action, version is @v4.

    - name: Debug SSH connection
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_IP }} "echo 'SSH Connection Successful'"

    - name: Copy files to VM
      run: |
        scp -r -i private_key -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} testScript.sh ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_IP }}:${{ secrets.pwd }}

    - name: Run setup script
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_IP }} 'sudo bash ${{ secrets.pwd }}testScript.sh > ${{ secrets.pwd }}output_$(date +%Y%m%d-%H%M-%S).txt'
